export const Images = [
  { Img: "./Assets/img1.png", name: "Stripes-Tallwalker" },
  { Img: "./Assets/img2.png", name: "Roadster" },
  { Img: "./Assets/img3.png", name: "Solbiza" },
  { Img: "./Assets/img4.png", name: "Casual Shirt" },
  { Img: "./Assets/img5.png", name: "Blue Black" },
  { Img: "./Assets/img6.png", name: "Stripes XL" },
  { Img: "./Assets/img7.png", name: "White Stripes" },
  { Img: "./Assets/img8.png", name: "Brown-XXL" },
  { Img: "./Assets/img9.png", name: "Checs original" },
  { Img: "./Assets/img10.png", name: "Double Pocket Green" },
  { Img: "./Assets/img11.png", name: "Roadster Original" },
  { Img: "./Assets/img12.png", name: "Checs original" },
  { Img: "./Assets/img13.png", name: "Pink Checs" },
  { Img: "./Assets/img14.png" ,name: "Formal" },
  { Img: "./Assets/img15.png" ,name: "Floral" },
  { Img: "./Assets/img16.png" ,name: "Floral" },
  { Img: "./Assets/img17.png" ,name: "Black Casual" },
  { Img: "./Assets/img18.png" ,name: "Floral" },
  { Img: "./Assets/img19.png" ,name: "Floral" },
  { Img: "./Assets/img20.png" ,name: "Casual" },
];
